// react/components/Dashboard.tsx

import React, { useMemo } from 'react';
import { User, Procurement, Submission, Role, ViewType, Language } from '../types';

interface DashboardProps {
  language: Language;
  t: any;
  user: User;
  procurements: Procurement[];
  submissions: Submission[];
  onNavigate: (view: ViewType) => void;
}

const Dashboard: React.FC<DashboardProps> = ({ language, t, user, procurements, submissions, onNavigate }) => {
  const isAdmin = user.role === Role.ADMIN_PROCUREMENT || user.role === Role.SUPER_ADMIN;

  const stats = [
    { label: t.dashboard.activeTenders, value: procurements.filter(p => p.status === 'OPEN').length, icon: 'fa-layer-group', color: 'text-blue-600' },
    { label: t.dashboard.totalSubmissions, value: submissions.length, icon: 'fa-clipboard-list', color: 'text-slate-600' },
    { label: user.role === Role.USER_PROCUREMENT ? t.dashboard.mySubmissions : t.dashboard.pendingReview, value: user.role === Role.USER_PROCUREMENT ? submissions.filter(s => s.userId === user.id).length : submissions.filter(s => s.status === 'PENDING').length, icon: 'fa-clock-rotate-left', color: 'text-amber-500' },
    { label: 'Avg Rating', value: user.ratings ? (user.ratings.reduce((a, b) => a + b, 0) / user.ratings.length).toFixed(1) : '4.8', icon: 'fa-star', color: 'text-blue-600' },
  ];

  return (
    <div className="space-y-10 animate-fadeIn">
      <header className="flex flex-col md:flex-row md:items-end justify-between gap-6 border-b border-slate-200 pb-8">
        <div>
          <h1 className="text-4xl font-black text-slate-900 tracking-tight">System Console</h1>
          <p className="text-slate-500 mt-2 font-medium">Monitoring procurement lifecycle and vendor engagement.</p>
        </div>
        <div className="flex items-center gap-4">
          <div className="text-right">
            <p className="text-[10px] font-black text-slate-400 uppercase tracking-widest">Environment</p>
            <p className="text-sm font-bold text-slate-900">Production Main</p>
          </div>
          <div className="w-10 h-10 rounded-xl bg-emerald-50 text-emerald-600 flex items-center justify-center border border-emerald-100 shadow-sm">
            <i className="fa-solid fa-server"></i>
          </div>
        </div>
      </header>

      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        {stats.map((stat, i) => (
          <div key={i} className="bg-white p-7 rounded-3xl border border-slate-200/60 shadow-sm transition-all hover:shadow-xl hover:shadow-blue-500/5 group hover:-translate-y-1">
            <div className="flex items-start justify-between mb-4">
              <div className={`w-10 h-10 rounded-xl bg-slate-50 ${stat.color} flex items-center justify-center text-sm border border-slate-100 transition-colors group-hover:bg-blue-50 group-hover:text-blue-600`}>
                <i className={`fa-solid ${stat.icon}`}></i>
              </div>
            </div>
            <p className="text-slate-400 text-[10px] font-black uppercase tracking-[0.15em] mb-1">{stat.label}</p>
            <p className="text-3xl font-black text-slate-900">{stat.value}</p>
          </div>
        ))}
      </div>

      <div className="grid grid-cols-1 xl:grid-cols-3 gap-8">
        <div className="xl:col-span-2 space-y-8">
          <div className="bg-white rounded-3xl border border-slate-200/60 overflow-hidden shadow-sm">
            <div className="p-8 border-b border-slate-100 flex items-center justify-between">
              <h2 className="text-lg font-bold text-slate-900 flex items-center gap-3">
                <i className="fa-solid fa-folder-tree text-blue-500"></i>
                Latest Procurements
              </h2>
              <button onClick={() => onNavigate('PROCUREMENTS')} className="text-xs font-bold text-blue-600 hover:text-blue-700 transition-colors uppercase tracking-widest">Global View</button>
            </div>
            <div className="divide-y divide-slate-50">
              {procurements.slice(0, 4).map(p => (
                <div key={p.id} className="p-6 flex items-center justify-between group hover:bg-slate-50 transition-colors">
                  <div className="flex-1">
                    <h3 className="text-sm font-bold text-slate-800 group-hover:text-blue-600 transition-colors">{p.title}</h3>
                    <div className="flex items-center gap-4 mt-1.5">
                      <span className="text-[10px] text-slate-400 font-bold uppercase tracking-widest">Budget: {p.budget}</span>
                      <span className="text-[10px] text-slate-400 font-bold uppercase tracking-widest">Until: {p.deadline}</span>
                    </div>
                  </div>
                  <div className={`px-3 py-1 rounded-full text-[9px] font-black uppercase tracking-tighter ${p.status === 'OPEN' ? 'bg-emerald-50 text-emerald-600' : 'bg-slate-100 text-slate-500'}`}>
                    {p.status}
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>

        <div className="space-y-8">
          <div className="bg-slate-900 rounded-3xl p-8 text-white relative overflow-hidden shadow-xl shadow-blue-500/10">
            <div className="relative z-10">
              <h3 className="text-lg font-bold mb-2">Internal Guidelines</h3>
              <p className="text-slate-400 text-sm leading-relaxed mb-6">All tender evaluations must follow the 2024 revised procurement standard ISO-9001.</p>
              <button className="w-full py-3 bg-blue-600 hover:bg-blue-700 rounded-xl text-xs font-bold transition-all shadow-lg shadow-blue-500/20">
                View Documentation
              </button>
            </div>
            <i className="fa-solid fa-shield-halved absolute -bottom-4 -right-4 text-8xl text-white/5 rotate-12"></i>
          </div>

          <div className="bg-white rounded-3xl border border-slate-200/60 p-8 shadow-sm">
            <h3 className="text-sm font-black text-slate-900 uppercase tracking-widest mb-6 border-b border-slate-50 pb-4">Live Activity</h3>
            <div className="space-y-6">
              {[1, 2].map(i => (
                <div key={i} className="flex gap-4">
                  <div className="w-2 h-2 rounded-full bg-blue-500 mt-1.5 flex-shrink-0"></div>
                  <div>
                    <p className="text-xs font-bold text-slate-800">New Submission Received</p>
                    <p className="text-[10px] text-slate-400 mt-1">Vendor PH Solutions applied to Cloud Upgrade.</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default Dashboard;

// sveltekit/src/routes/dashboard/+page.svelte
<script lang="ts">
	import { appState } from '$lib/state.svelte';
	import StatCard from '$lib/components/StatCard.svelte';
	import ProcurementCard from '$lib/components/ProcurementCard.svelte';
	import { fade, fly } from 'svelte/transition';

	const t = $derived(appState.t.dashboard);

	const recentProcurements = [
		{
			id: '1',
			title: 'Cloud Infrastructure Upgrade 2024',
			type: 'Enterprise',
			amount: '$500,000',
			deadline: '31 Dec 2024'
		},
		{
			id: '2',
			title: 'Office Hardware Renewal',
			type: 'Operational',
			amount: '$85,000',
			deadline: '15 Nov 2024'
		},
		{
			id: '3',
			title: 'Security Audit Services',
			type: 'Compliance',
			amount: '$120,000',
			deadline: '20 Oct 2024'
		}
	];
</script>

<div class="space-y-16 py-8" in:fade={{ duration: 800 }}>
	<header class="space-y-2">
		<h2 class="text-5xl font-black tracking-tight text-slate-900 lg:text-6xl">
			{t.welcome}, <span class="text-blue-600">{appState.currentUser?.name || 'User'}</span>
		</h2>
		<p class="max-w-2xl text-lg leading-relaxed font-medium text-slate-400">{t.overview}</p>
	</header>

	<div class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-4">
		<div in:fly={{ y: 20, duration: 600, delay: 100 }}>
			<StatCard
				title={t.status}
				value="Procurify v1.4"
				icon="terminal"
				status={t.operational}
				variant="blue"
			/>
		</div>
		<div in:fly={{ y: 20, duration: 600, delay: 200 }}>
			<StatCard title={t.activeTenders} value="12 Active" icon="work" variant="amber" />
		</div>
		<div in:fly={{ y: 20, duration: 600, delay: 300 }}>
			<StatCard title={t.totalSubmissions} value="84 Total" icon="description" variant="purple" />
		</div>
		<div in:fly={{ y: 20, duration: 600, delay: 400 }}>
			<StatCard title={t.completed} value="156 Units" icon="verified" variant="blue" />
		</div>
	</div>

	<div class="grid grid-cols-1 gap-12 lg:grid-cols-3">
		<div class="space-y-8 lg:col-span-2">
			<div class="flex items-center justify-between">
				<h4 class="text-sm font-black tracking-[0.2em] text-slate-400 uppercase">
					{t.recentProc}
				</h4>
				<button
					class="text-xs font-black tracking-widest text-blue-600 uppercase transition-all hover:translate-x-1 hover:opacity-70"
				>
					{t.viewAll} →
				</button>
			</div>

			<div class="grid gap-4">
				{#each recentProcurements as proc, i}
					<div in:fly={{ x: -20, duration: 500, delay: 500 + i * 100 }}>
						<ProcurementCard
							id={proc.id}
							title={proc.title}
							type={proc.type}
							amount={proc.amount}
							deadline={proc.deadline}
							deadlineLabel={t.deadline}
						/>
					</div>
				{/each}
			</div>
		</div>

		<div class="space-y-8">
			<h4 class="text-sm font-black tracking-[0.2em] text-slate-400 uppercase">
				{t.actionItems}
			</h4>
			<div
				class="group relative flex min-h-[400px] flex-col justify-between overflow-hidden rounded-[3rem] bg-slate-950 p-10 text-white shadow-2xl shadow-slate-900/40"
				in:fly={{ x: 20, duration: 600, delay: 800 }}
			>
				<div
					class="absolute -top-20 -right-20 h-64 w-64 rounded-full bg-blue-500/10 blur-[80px] transition-all duration-700 group-hover:bg-blue-500/20"
				></div>

				<div class="relative z-10 space-y-6">
					<div
						class="inline-flex h-12 w-12 items-center justify-center rounded-xl bg-white/10 text-blue-400 backdrop-blur-sm"
					>
						<span class="material-symbols-outlined text-2xl">bolt</span>
					</div>
					<div class="space-y-2">
						<h5 class="text-xl font-bold tracking-tight">Review Submissions</h5>
						<p class="text-sm leading-relaxed font-medium text-slate-400">
							{t.actionDesc}
						</p>
					</div>

					<div class="flex items-center gap-4">
						<div class="flex -space-x-4">
							{#each Array(3) as _, i}
								<img
									src="https://i.pravatar.cc/100?u={i}"
									alt="Vendor"
									class="h-10 w-10 rounded-xl border-2 border-slate-950 object-cover shadow-lg transition-transform hover:z-20 hover:scale-110"
								/>
							{/each}
						</div>
						<div class="space-y-0.5">
							<span class="block text-xs font-black tracking-widest text-blue-400 uppercase">
								+5 {t.pendingCount}
							</span>
							<span class="block text-[10px] font-bold tracking-tight text-slate-500 uppercase"
								>Requires Attention</span
							>
						</div>
					</div>
				</div>

				<button
					class="relative z-10 w-full rounded-2xl bg-blue-600 py-5 text-xs font-black tracking-[0.3em] uppercase shadow-lg shadow-blue-600/20 transition-all hover:bg-blue-500 hover:shadow-blue-500/40 active:scale-95"
				>
					{t.reviewAll}
				</button>
			</div>
		</div>
	</div>
</div>
